# example netlify.toml
[build]
  command = "astro build"
  functions = "netlify/functions"
  publish = "dist"

[[plugins]] 
  #there are no plugins 
  
  [plugins.inputs.postBuild]
    enable = true
  
  [plugin.inputs]
    enable = false